services:
  downdetector-api:
    build: .
    image: downdetector-api:latest
    container_name: downdetector-api
    env_file:
      - .env
    environment:
      BROWSER_USER_DATA_DIR: /browser-data
    shm_size: "1gb"
    volumes:
      - browser-data:/browser-data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.downdetector-api.rule=Host(`${TRAEFIK_HOST:?Configure TRAEFIK_HOST no .env}`)"
      - "traefik.http.routers.downdetector-api.entrypoints=websecure"
      - "traefik.http.routers.downdetector-api.tls.certresolver=le"
      - "traefik.http.services.downdetector-api.loadbalancer.server.port=8000"
    networks:
      - traefik
      - downdetector-network
    restart: unless-stopped

networks:
  traefik:
    external: true
  downdetector-network:
    driver: bridge

volumes:
  browser-data:
